# Versión de docker-compose
version: '3'
services:
  besu-node1:
    # Imagen de Besu utilizada para el nodo
    image: hyperledger/besu:26.2.0
    # Nombre de host del contenedor
    hostname: besu_node1
    # Política de reinicio del contenedor
    restart: always
    # Volúmenes montados (directorio local en el contenedor)
    volumes:
      - .:/var/lib/besu/QBFT-Network
    # Puertos expuestos y mapeados del host al contenedor
    ports:
      # Puerto para la API JSON-RPC HTTP (por defecto 8545)
      - 8545:8545
      # Puerto para la API JSON-RPC WebSocket (por defecto 8546)
      - 8546:8546
      # Puerto para comunicación P2P entre nodos (TCP, por defecto 30303)
      - 30303:30303
      # Puerto para comunicación P2P entre nodos (UDP)
      - 30303:30303/udp
    # Comando de inicio de Besu con la ruta al archivo de configuración
    command: --config-file=/var/lib/besu/QBFT-Network/configNodes/node-config_1.toml
    # Variables de entorno
    environment:
      # Ruta al archivo de clave privada del nodo
      - BESU_NODE_PRIVATE_KEY_FILE=/var/lib/besu/QBFT-Network/networkFiles/keys/key1
      # Configuración para estadísticas de red EthStats
      - BESU_ETHSTATS=2nodeNetwork_1:asdf@192.168.100.10:3000
    # Conexión a la red definida en "networks"
    networks:
      - besu_network

networks:
  besu_network:
    # Nombre de la red a crear o utilizar
    name: besu_network
    # Driver de red de Docker (bridge por defecto)
    driver: bridge
